# Use the official Python image
FROM python:3.9

# Set working directory
WORKDIR /usr/src/app

# Copy the code from the host machine to the container
COPY . .

# Run the Python script
CMD ["python3", "code.py"]
